version: "3.7"
services:
  #PHP Service
  dphe:
    build:
      args:
        user: dream71
        uid: 1000
      context: .
      dockerfile: .docker/Dockerfile
    image: dphe
    restart: unless-stopped
    working_dir: /var/www/
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - dphe_network

  #MySQL Service
  dphe_db:
    image: mysql:8.0
    container_name: dphe_db
    restart: unless-stopped
    ports:
      - "${DOCKER_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dphe_mysql_data:/var/lib/mysql
    networks:
      - dphe_network

  #Nginx Service
  dphe_nginx:
    image: nginx:alpine
    container_name: dphe_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_APP_PORT}:80"
      - "${DOCKER_APP_SSL_PORT}:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./.docker/nginx/certs:/etc/nginx/certs
    networks:
      - dphe_network
  # phpmyadmin service
  dphe_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: dphe_phpmyadmin
    depends_on:
      - dphe_db
    ports:
      - "${DOCKER_PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: dphe_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 300M
    networks:
      - dphe_network

  dphe_redis_cache:
    image: redis:alpine
    restart: always
    container_name: dphe_redis_cache
    ports:
      - '${DOCKER_REDIS_PORT}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - dphe_cache:/data
    networks:
      - dphe_network

#Docker Networks
networks:
  dphe_network:
    driver: bridge

#Volumes
volumes:
  dphe_mysql_data:
  dphe_cache:
